# Generated by Django 3.2.7 on 2021-10-06 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211001_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=150)),
                ('via', models.CharField(max_length=150)),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
